version: '3'
services:
  envoy:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    env_file:
      - .env
  simpleapi:
    build: SimpleAPI/
    #expose:
    #  - "80"
    #  - "443"
    ports:
      - "5000:80"
      - "5001:443"
    environment: 
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes: 
      - ${APPDATA}\Microsoft\UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    env_file:
      - .env